# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
